#! /usr/bin/env python

import os
import os.path
import sys
import subprocess

zeroes = []
ones = []
for fn in os.listdir('waves_yesno'):
    if fn.startswith('1'):
        ones.append(fn)


def text_test(filenames):
    results = []
    for filename in filenames:
        basename = filename.split('.')[0]
        #transcript = basename.replace('1', 'YES').replace('0', 'NO').replace('_', " ")
        results.append("{} {} {} {} {} {} {} {}".format(basename.split('.')[0], "YES","YES","YES","YES","YES","YES","YES","YES"))

    return '\n'.join(sorted(results))


with open('data/test_yesno/text', 'w') as test_text:
    test_text.write(text_test(ones))

# finish this method
def wav_scp(file):
    results = []
    for filename in file:
        basename = filename.split('.')[0]
        
        #transcript = basename.replace('1', 'YES').replace('0', 'NO').replace('_', " ")
        results.append("{} {}{}{}".format(basename.split('.')[0], "waves_yesno/",basename.split('.')[0],".wav"))

    return '\n'.join(sorted(results))

with open('data/test_yesno/wav.scp', 'w') as test_text:
    #train_text.write(wav_scp(zeroes))
    test_text.write(wav_scp(ones))


# finish this method
def utt2spk(files):
    results=[]
    for filename in files:
        basename=filename.split('.')[0]
        #print(basename.split('.')[0])
        results.append("{} {}".format(basename.split('.')[0],"global"))
    return '\n'.join(sorted(results))

with open('data/test_yesno/utt2spk', 'w') as test_text:
    #train_text.write(utt2spk(zeroes))
    test_text.write(utt2spk(ones))


# finish this method
# note that, spk2utt can be generated by using Kaldi util, once you have utt2spk file.
def spk2utt(files):
    results=[]
    for filename in files:
        basename=filename.split('.')[0]
        #print(basename.split('.')[0])
        results.append("{} {}".format("global",basename.split('.')[0]))
    return '\n'.join(sorted(results))

with open('data/test_yesno/spk2utt', 'w') as test_text:
    test_text.write(spk2utt(ones))